---
title: 'Whats next?'
teaching: 10
exercises: 2
link-external-newwindow: true
---

:::::::::::::::::::::::::::::::::::::: questions 

- "What is the next step?"

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- "Get an idea about what to do to learn more"

::::::::::::::::::::::::::::::::::::::::::::::::


Dedicated packages exist for interacting with many of the larger content and data providers. 
Many of the larger content and data providers.


The [gargle package](https://cran.r-project.org/web/packages/gargle/index.html){target="_blank"},
provides tools for working with the Google APIs.

[The Guardian](https://open-platform.theguardian.com/){target="_blank"} have an open API providing
access to >2 million articles from that newspaper. You will need to register for
an API key, but it is free. And the [guardianapi](https://cran.r-project.org/web/packages/guardianapi/index.html){target="_blank"} package makes this easy.

[Wikidata](https://www.wikidata.org/wiki/Wikidata:REST_API){target="_blank"} handles factual data
for the Wikipedia infrastructure, and have a dedicated package: [WikidataR](https://cran.r-project.org/web/packages/WikidataR/index.html){target="_blank"}



You can find other courses, covering other aspects of R in our course calendars:

- [Roskilde University Library](https://roskildeuni.libcal.com/){target="_blank"}
- [Copenhagen University Library](https://kubkalender.kb.dk/calendar/datalab?cid=6416&t=d&d=0000-00-00&cal=6416&inc=0){target="_blank"}



::::::::::::::::::::::::::::::::::::: keypoints 

- "Practice makes perfect"
- "KUB Datalab offers lots of courses and consultations"
- "The web is overflowing with tutorials and courses"

::::::::::::::::::::::::::::::::::::::::::::::::

